name: 'Setup asset of Github Releases'
description: 'GitHub Action for gh-setup'
inputs:
  github-token:
    description: The GitHub token
    default: ${{ github.token }}
    required: false
  repo:
    description: "Target repository [OWNER/REPO]"
    required: true
  bin-dir:
    description: "Executable path"
    default: ""
    required: false
  version:
    description: "Release version"
    default: ""
    required: false
  os:
    description: "Specify OS of asset"
    default: ""
    required: false
  arch:
    description: "Specify arch of asset"
    default: ""
    required: false
  match:
    description: "Match string for asset"
    default: ""
    required: false
  force:
    description: "Enable force setup"
    default: ""
    required: false
  gh-setup-version:
    description: "Version of gh-setup"
    default: "v0.6.0"
    required: false
runs:
  using: "composite"
  steps:
    -
      id: install-gh-setup
      run: scripts/install-gh-setup.sh
      shell: bash
      env:
        GH_SETUP_GITHUB_TOKEN: ${{ inputs.github-token }}
        GH_SETUP_GH_SETUP_VERSION: ${{ inputs.gh-setup-version }}
    -
      run: scripts/run-gh-setup.sh
      shell: bash
      env:
        GH_SETUP_GITHUB_TOKEN: ${{ inputs.github-token }}
        GH_SETUP_REPO: ${{ inputs.repo }}
        GH_SETUP_BIN_DIR: ${{ inputs.bin-dir }}
        GH_SETUP_VERSION: ${{ inputs.version }}
        GH_SETUP_OS: ${{ inputs.os }}
        GH_SETUP_ARCH: ${{ inputs.arch }}
        GH_SETUP_FORCE: ${{ inputs.force }}
        GH_SETUP_BIN: ${{ steps.install-gh-setup.outputs.bin }}
