#!/bin/bash
set -e

repo="github.com/k1LoW/gh-setup"

extensionPath="$(dirname "$0")"
cd "${extensionPath}" > /dev/null
tag="$(git tag | tail -1)"
cd - > /dev/null

arch="$(uname -m)"

exe=""

if uname -a | grep Msys > /dev/null; then
  if [ $arch = "x86_64" ]; then
    exe="gh-setup_${tag}_windows_amd64.exe"
  fi
elif uname -a | grep Darwin > /dev/null; then
  if [ $arch = "x86_64" ]; then
    exe="gh-setup_${tag}_darwin_amd64"
  elif [ $arch = "arm64" ]; then
    exe="gh-setup_${tag}_darwin_arm64"
  fi
elif uname -a | grep Linux > /dev/null; then
  if [ $arch = "x86_64" ]; then
    exe="gh-setup_${tag}_linux_amd64"
  fi
fi

if [ "${exe}" == "" ]; then
  if [ "$(which go)" = "" ]; then
    echo "go must be installed to use this gh extension on this platform"
    exit 1
  fi

  exe="cmd.out"

  cd "${extensionPath}" > /dev/null
  go build -o "${exe}" cmd/gh-setup/main.go
  cd - > /dev/null
  mv "${exe}" "${extensionPath}/bin/${exe}"
  chmod +x "${extensionPath}/bin/${exe}"
else
  if [[ ! -x "${extensionPath}/bin/${exe}" ]]; then
    mkdir -p "${extensionPath}/bin"
    rm -f ${extensionPath}/bin/gh-setup*
    gh release -R "${repo}" download "${tag}" -p "${exe}" --dir="${extensionPath}/bin"
    chmod +x "${extensionPath}/bin/${exe}"
  fi
fi

exec "${extensionPath}/bin/${exe}" "$@"
